FROM rclone/rclone


FROM node:18-alpine
RUN apk add --no-cache libc6-compat python3 make g++ make
WORKDIR /app
COPY ./tsconfig.json ./package.json ./entry.sh /app/
COPY ./src /app/src/
RUN cd /app \
    && yarn install --dev

COPY --from=0 /usr/local/bin/rclone /usr/local/bin/rclone
RUN addgroup -g 1009 rclone && adduser -u 1009 -Ds /bin/sh -G rclone rclone
ENV XDG_CONFIG_HOME=/config

ENV PORT 4000
ENV HOST 0.0.0.0
ENV NODE_ENV development
ENV DATA_DIR /data
ENV RCLONE_PORT 5001
ENV RCLONE_ADDR localhost:$RCLONE_PORT

ENTRYPOINT ["/app/entry.sh"]
CMD ["/app/node_modules/.bin/ts-node-dev", "--transpile-only", "./src/server.ts"]