FROM lukechannings/deno

RUN apt update -y
RUN apt install -y unzip curl jq

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install -y nodejs && corepack enable

WORKDIR /app
COPY ./tsconfig.json ./package.json ./entry.sh /app/
RUN cd /app \
    && jq -c 'del(.devDependencies)' package.json > package.json.tmp \
    && mv package.json.tmp package.json \
    && npm install --omit=dev --omit=optional \
    && npm install -g node-dev
COPY ./dist /app/dist/
COPY ./entry.sh /app/entry.sh
RUN mkdir -p /var/workflows /var/actions /var/system-workflows /var/workflow /data
COPY ./workflows /var/system-workflows

ENV ACTIONS_DIR /var/actions
ENV WORKFLOWS_DIR /var/workflows
ENV DATA_DIR /data
ENV WORKING_DIR /var/workflow
ENV PORT 4000
ENV HOST 0.0.0.0

ENTRYPOINT ["/app/entry.sh"]
CMD ["node-dev", "./dist/server.js"]