FROM lukechannings/deno

RUN apt update -y
RUN apt install -y unzip curl jq

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install -y nodejs && corepack enable

WORKDIR /app
RUN cd /app \
    && npm install -g node-dev \
    && npm install
COPY ./dist /app/dist/
COPY ./entry.sh /app/entry.sh
COPY ./workflows /var/system-workflows
RUN mkdir -p /var/workflows /var/actions /var/system-workflows /var/workflow /data


ENV ACTIONS_DIR /var/actions
ENV WORKFLOWS_DIR /var/workflows
ENV DATA_DIR /data
ENV WORKING_DIR /var/workflow
ENV PORT 3002
ENV HOST 0.0.0.0
ENV LAUNCH_MODE UNIVERSAL

ENTRYPOINT ["/app/entry.sh"]
CMD ["node-dev", "./dist/entry.js"]