name: "hello_world"
when: "{% event === 'hello-world' %}"
jobs:
  default:
    description: "I say 'Hello World'"
    steps:
      - action: "run/echo"
        input:
          message: "${ input.message }"
