name: "hello_world"
when: "{% event === 'hello-world' %}"
jobs:
  default:
    description: "I say 'Hello World'"
    input:
      object: "${ input.object }"
    steps:
      - action: "run/echo"
        input:
          message: "{%= toJson(input.object) %}"
