name: Release

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  images:
    name: ${{ matrix.name }} Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: DB
            dir: ./services/db
            image: ghcr.io/elwood-studio/db
            context: ./services/db
            build: false
            platforms: linux/amd64,linux/arm64

          - name: Gateway
            dir: ./services/gateway
            image: ghcr.io/elwood-studio/gateway
            context: ./services/gateway
            build: false
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

          - name: File System
            dir: ./services/fs
            image: ghcr.io/elwood-studio/fs
            context: ./services/fs
            build: true
            platforms: linux/amd64,linux/arm64

          - name: Workflow
            dir: ./services/workflow
            image: ghcr.io/elwood-studio/workflow
            context: ./services/workflow
            build: true
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # only need to run node setup
      # if the image requires a build
      # call before building
      - uses: actions/setup-node@v3
        if: ${{ matrix.build }}

      - uses: pnpm/action-setup@v2
        if: ${{ matrix.build }}
        with:
          version: 8

      - run: make ready
        if: ${{ matrix.build }}

      # end if build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dir }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          platforms: ${{ matrix.platforms }}

      # save cache for build
      - name: Get pnpm store directory
        if: ${{ matrix.build }}
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        if: ${{ matrix.build }}
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: config git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Elwood Studio"
          git config --global user.email "security@elwood.studio"

      - run: make install
      - run: make version
      - run: make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
